import './globals.css'
import type { Metadata } from 'next'
import { poppins, pressStart } from "./fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.variable} ${pressStart.variable}`}>{children}</body>
    </html>
  )
}
